#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-expose-admin-cmd() {
  #E expose the service's admin UI on a specific domain.
  #E dokku $PLUGIN_COMMAND_PREFIX:expose-admin lollipop lollipop.dokku.me
  declare desc="expose a $PLUGIN_SERVICE service's admin on the specified domain"
  local cmd="$PLUGIN_COMMAND_PREFIX:expose-admin" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" DOMAIN="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
  [[ -z "$DOMAIN" ]] && dokku_log_fail "Please specify a valid domain for the service"
  verify_service_name "$SERVICE"
  service_expose_admin "$SERVICE" "$DOMAIN"
}

service-expose-admin-cmd "$@"
