#!/usr/bin/env bash
set -eo pipefail

[[ "$DOKKU_TRACE" ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"

cmd-service-unlink() {
    declare desc="unlink the $PLUGIN_SERVICE service from the app"
    local cmd="$PLUGIN_COMMAND_PREFIX:unlink" argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    declare SERVICE="$1" APP="$2"
    APP=${APP:="$DOKKU_APP_NAME"}

    [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
    [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
    verify_app_name "$APP"
    verify_service_name "$SERVICE"

    service_unlink "$SERVICE" "$APP"
}

cmd-service-unlink "$@"
